version: '3'

services:
  postgres:
    image: docker.io/postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: your_username
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  #keycloak:
  #  image: quay.io/keycloak/keycloak:15.0.2
  #  environment:
  #    KEYCLOAK_USER: admin
  #    KEYCLOAK_PASSWORD: admin
  #  ports:
  #    - "8081:8080"
  #  depends_on:
  #    - postgres
#
  urlshortener:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urlshortener
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password
      KEYCLOAK_SERVER_URL: http://keycloak:8081/auth
      KEYCLOAK_REALM: urlshortener
      KEYCLOAK_RESOURCE: urlshortener-api
    depends_on:
      - keycloak
      - postgres

volumes:
  db_data:
